-- SQL Dump Generated from CSV
START TRANSACTION;

CREATE TABLE `users` (
  `id` INT NOT NULL,
  `FFusername` TEXT NOT NULL,
  `FFpassword` TEXT NOT NULL,
  `FFname` TEXT NOT NULL,
  `picture` TEXT NOT NULL,
  `activity_level` DECIMAL NOT NULL,
  `food_level` DECIMAL NOT NULL,
  `recovery_level` DECIMAL NOT NULL,
  `activity_goal` DECIMAL NOT NULL,
  `food_goal` DECIMAL NOT NULL,
  `recovery_goal` DECIMAL NOT NULL
  , PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserting data from CSV
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('1', 'fitfan01', 'Strong@2024', 'Emily Johnson', 'pictures/girl1.jpg', '5', '3215', '35', '110', '3400', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('2', 'healthguru99', 'Workout*123', 'Michael Smith', 'pictures/guy1.jpg', '35', '655', '40', '40', '3500', '90');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('3', 'cardioqueen22', 'Flexibility!456', 'Sarah Williams', 'pictures/girl2.jpg', '25', '840', '20', '110', '4000', '65');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('4', 'yogi_bear88', 'Zen&789', 'David Brown', 'pictures/guy2.jpg', '10', '1180', '20', '90', '3100', '30');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('5', 'strengthcoach33', 'PowerLift$321', 'Jessica Taylor', 'pictures/girl3.jpg', '110', '1490', '80', '110', '2600', '120');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('6', 'gymrat54', 'Cardio#7890', 'James Anderson', 'pictures/guy3.jpg', '70', '485', '35', '120', '3000', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('7', 'nutritionista77', 'EatWell%2023', 'Amanda Martinez', 'pictures/girl4.jpg', '65', '1660', '20', '115', '1700', '75');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('8', 'runforfun101', 'RunFast!2024', 'John Garcia', 'pictures/guy4.jpg', '15', '160', '55', '55', '2900', '65');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('9', 'pilateslover11', 'Stretch&456', 'Lisa Robinson', 'pictures/girl5.jpg', '30', '615', '25', '115', '1800', '30');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('10', 'healthy_habits29', 'FreshStart#567', 'Karen Lewis', 'pictures/girl6.jpg', '25', '1245', '60', '60', '3200', '100');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('11', 'fitness_freak18', 'FitLife@123', 'Brian Hall', 'pictures/guy5.jpg', '45', '515', '85', '45', '2500', '95');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('12', 'weightloss_wiz44', 'SlimDown$789', 'Angela Young', 'pictures/girl7.jpg', '30', '2345', '20', '80', '3300', '45');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('13', 'workout_warrior77', 'Tough@2024', 'Timothy King', 'pictures/guy6.jpg', '45', '2060', '20', '50', '2900', '45');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('14', 'zenmaster45', 'Calm*1234', 'Sophia Wright', 'pictures/girl8.jpg', '80', '470', '15', '120', '2100', '80');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('15', 'powerlifter99', 'HeavyLift&321', 'Daniel Lee', 'pictures/guy7.jpg', '5', '10', '25', '40', '3100', '60');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('16', 'runner_girl12', 'RunStrong%456', 'Melissa Turner', 'pictures/girl9.jpg', '55', '1025', '15', '85', '2500', '30');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('17', 'yogawonder34', 'Yoga4Life!789', 'Jessica White', 'pictures/girl10.jpg', '10', '2610', '75', '85', '3600', '85');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('18', 'cardio_connoisseur', 'HeartRate$123', 'Christopher Scott', 'pictures/guy8.jpg', '15', '835', '30', '35', '1600', '60');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('19', 'strength_enthusiast', 'Iron@2023', 'Patricia Hill', 'pictures/girl11.jpg', '10', '1790', '35', '35', '1800', '40');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('20', 'gymbuddy88', 'GymTime#456', 'Kevin Scott', 'pictures/guy9.jpg', '0', '2065', '40', '35', '3500', '45');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('21', 'fitspiration2023', 'Inspire*789', 'Megan Adams', 'pictures/girl12.jpg', '5', '2545', '105', '30', '3500', '120');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('22', 'active_adventurer', 'Explore@321', 'Laura Green', 'pictures/girl13.jpg', '50', '10', '30', '100', '2600', '75');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('23', 'wellness_warrior', 'Heal!2024', 'Charles Walker', 'pictures/guy10.jpg', '95', '435', '0', '110', '4000', '50');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('24', 'cycling_champ101', 'BikeFast&456', 'Sarah Evans', 'pictures/girl14.jpg', '10', '365', '35', '70', '3200', '90');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('25', 'fitness_junkie55', 'Cardio@7890', 'Jonathan Hall', 'pictures/guy11.jpg', '25', '1505', '75', '35', '2600', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('26', 'mindful_mover42', 'Balance$1234', 'Lisa Campbell', 'pictures/girl15.jpg', '80', '730', '100', '100', '1800', '110');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('27', 'healthy_hustler44', 'Hustle&456', 'Aaron Clark', 'pictures/guy12.jpg', '10', '2080', '15', '120', '2500', '55');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('28', 'fitfamily88', 'Together@2024', 'Michelle Nelson', 'pictures/girl16.jpg', '5', '1745', '0', '45', '2000', '70');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('29', 'strong_sister11', 'SisterPower%789', 'Emily Carter', 'pictures/girl17.jpg', '30', '440', '80', '30', '2400', '95');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('30', 'cardio_king22', 'Sprint!123', 'Steven Lewis', 'pictures/guy13.jpg', '0', '250', '60', '85', '2300', '70');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('31', 'wellness_whiz29', 'Wellness*2024', 'Angela Martinez', 'pictures/girl18.jpg', '75', '745', '80', '85', '2200', '110');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('32', 'nutrition_ninja66', 'Foodie@456', 'Jessica Perez', 'pictures/girl19.jpg', '15', '1565', '25', '55', '2800', '50');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('33', 'power_pants101', 'LiftHeavy#789', 'Ashley Bennett', 'pictures/girl20.jpg', '70', '1360', '25', '70', '2500', '60');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('34', 'running_royalty77', 'Run&Smile$321', 'William Mitchell', 'pictures/guy14.jpg', '45', '2435', '50', '55', '3700', '85');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('35', 'yogini23', 'Mindful!1234', 'Sophia Young', 'pictures/girl21.jpg', '35', '725', '0', '40', '1600', '40');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('36', 'fit_enthusiast22', 'Healthy&456', 'Alexander Johnson', 'pictures/guy15.jpg', '50', '360', '15', '65', '3200', '55');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('37', 'gym_goddess44', 'Goddess@2023', 'Rachel Hill', 'pictures/girl22.jpg', '20', '690', '25', '35', '1600', '45');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('38', 'fitness_fanatic', 'Fanatic#789', 'Christina Lee', 'pictures/girl23.jpg', '5', '1780', '45', '90', '2500', '95');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('39', 'wellness_lover18', 'LoveLife%321', 'Kimberly Taylor', 'pictures/girl24.jpg', '40', '2865', '45', '60', '3800', '110');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('40', 'muscle_master12', 'Master!456', 'Kevin Garcia', 'pictures/guy16.jpg', '15', '380', '10', '35', '2000', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('41', 'running_hero33', 'Hero@7890', 'Nathan Roberts', 'pictures/guy17.jpg', '5', '90', '35', '60', '2800', '55');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('42', 'holistic_hiker21', 'HikeStrong*2024', 'Olivia Sanchez', 'pictures/girl25.jpg', '40', '2275', '115', '85', '2300', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('43', 'stretch_savant77', 'Stretch&1234', 'Sophia Kim', 'pictures/girl26.jpg', '30', '2150', '15', '50', '3600', '115');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('44', 'fit_squad55', 'Squad$456', 'Michael Robinson', 'pictures/guy18.jpg', '70', '570', '55', '120', '2700', '95');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('45', 'zen_zest45', 'Zesty@789', 'Isabella Wright', 'pictures/girl27.jpg', '45', '1555', '5', '45', '2400', '40');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('46', 'total_body_tamer', 'Tame@2024', 'Benjamin Hall', 'pictures/guy19.jpg', '0', '585', '50', '50', '2600', '90');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('47', 'strong_legacy66', 'Legacy%1234', 'Ava Anderson', 'pictures/girl28.jpg', '80', '2990', '5', '110', '3100', '35');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('48', 'fit_for_life77', 'ForLife!2023', 'Jackson Moore', 'pictures/guy20.jpg', '5', '2630', '0', '35', '3500', '35');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('49', 'workout_wizard11', 'Wizard*456', 'Charlotte Lewis', 'pictures/girl29.jpg', '15', '1545', '10', '45', '3100', '120');
INSERT INTO `users` (`id`, `FFusername`, `FFpassword`, `FFname`, `picture`, `activity_level`, `food_level`, `recovery_level`, `activity_goal`, `food_goal`, `recovery_goal`) VALUES ('50', 'cardio_conqueror', 'Conquer!789', 'Henry Thompson', 'pictures/guy21.jpg', '15', '1540', '0', '40', '3500', '35');

-- Setting AUTO_INCREMENT to continue from max id + 1
ALTER TABLE `users` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

COMMIT;
